#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-5 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 11 12 13 14 15 16 17 18 19 20

# bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# "Services" autostart
setxkbmap latam
xinput --set-prop 'pointer:Logitech G305' 'Coordinate Transformation Matrix' 0.4 0 0 0 0.4 0 0 0 1
xsetroot -cursor_name left_ptr &
xset s 0 0 -dpms
lxsession &
picom --experimental-backend --config $HOME/.config/picom/picom.conf &
~/.fehbg &
$HOME/.config/polybar/launch.sh &
rclone --vfs-cache-mode writes mount onedrive: ~/onedrive

# Applications autostart
bspc rule -a Thunderbird desktop=18
bspc rule -a discord desktop=19
bspc rule -a Steam desktop=10
thunderbird &
discord &
steam &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
